width=300
margin=10
padding=8

background-color={{background}}
text-color={{foreground}}
border-color={{color8}}

border-size=2
border-radius=4

font=sans-serif 10
markup=1
icons=1
max-icon-size=32
max-history=5
format=<b>%s</b>\n%b

[urgency=low]
background-color={{color0}}
border-color={{color8}}

[urgency=normal]
border-color={{color4}}

[urgency=critical]
border-color={{color1}}
text-color={{color1}}
