
exec-once = systemctl --user start hyprpolkitagent 
exec-once = vicinae server
exec-once = hypridle 
exec-once = awww-daemon

exec-once = swaync -s ~/.config/swaync/style.css 
exec-once = waybar
exec-once = ~/.config/hypr/shaders/shader-picker.sh init
exec-once = hyprctl setcursor MacTahoe-dark 30
