
exec-once = systemctl --user start hyprpolkitagent 
exec-once = vicinae server
exec-once = nm-applet 
exec-once = hypridle 
exec-once = awww-daemon
exec-once = waypaper --restore

exec-once = hyprfloat
exec-once = swaync -s ~/.config/swaync/style.css 
exec-once = waybar
exec-once = gnome-keyring-daemon --start --components=secrets
