# --- Monitor Configuration ---
monitor = , 1920x1080@60, auto, 1.0

# --- Input Configuration ---
input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
        tap-to-click = true
    }
}
cursor {
  hide_on_key_press = true
}

gestures {
    # The one you already have
    gesture = 3, horizontal, workspace
}
