windowrule {
  name = localsend
  match:class = ^(localsend)$
  float = on 
  center = on 
  size = 720 480
}

windowrule {
    name = firefox-pop-up-sign-in-window
    match:title = ^(Sign in - Google Accounts|Google Accounts|Sign in|Login|Authorize.*)$
    match:class = ^(firefox.*|Firefox)$
    float = on
    size = 600 450
    center = on
    pin = on
}

windowrule {
    name = firefox-file-picker
    # Match standard GTK/XDG dialog titles commonly triggered by Firefox
    match:title = ^(.*wants to save.*|Open File|Save File|Save Image|Save As|Select Folder|Enter name of file to save to.*)$
    match:class = ^(firefox|Firefox)$
    
    float = on
    size = 900 600
    center = on
    pin = on
}

windowrule {
    name = firefox-file-input-picker
    match:title = ^(.*wants to (open|save).*|Open File|Save File|Save Image|Save As|Select Folder.*)$
    match:initial_class = ^(firefox|Firefox)$

    float = on
    size = 900 600
    center = on
    pin = on
}

windowrule {
    name = firefox-picture-in-picture
    match:title = ^(Picture-in-Picture)$
    match:class = ^(firefox.*|Firefox)$
    
    float = on
    pin = on 
    size = 480 270
    min_size = 480 270
    max_size = 480 270
    keep_aspect_ratio = off
    suppress_event = maximize fullscreen 
  }

windowrule {
    name = small-file-picker
    match:class = ^(xdg-desktop-portal-gnome)$
    float = 1
    size = 800 600
    center = 1
    pin = on
}

windowrule {
  name = files
  match:class = ^(waypaper)$
  float = on 
  center = on 
  size = 1200 800
}

