layerrule {
    name = waybar-animation
    match:namespace = ^(waybar)$
    animation = slide
}

windowrule {
    name = scrcpy-phone-popover
    match:class = ^(scrcpy)$
    float = on
    pin = on
    size = 405 900
}

windowrule {
name = brave-pop-up-sign-in-window
match:title = ^(Sign in - Google Accounts|Google Accounts|Sign in|Login|Authorize.)$
match:class = ^(brave-browser.|Brave-browser|brave)$
float = on
size = 600 450
center = on
pin = on
}

windowrule {
name = brave-file-picker
match:title = ^(.wants to save.|Open File|Save File|Save Image|Save As|Select Folder|Enter name of file to save to.)$
match:class = ^(brave-browser.|Brave-browser|brave)$
float = on
size = 900 600
center = on
pin = on
}

windowrule {
name = brave-file-input-picker
match:title = ^(.wants to (open|save).|Open Files|Open File|Save File|Save Image|Save As|Select Folder.)$
match:initial_class = ^(brave-browser.|Brave-browser|brave)$
float = on
size = 900 600
center = on
pin = on
}

windowrule {
name = brave-picture-in-picture
match:title = ^(Picture in picture)$
match:class = ^(brave-browser.*|Brave-browser|brave)$
float = on
pin = on
size = 480 270
keep_aspect_ratio = off
suppress_event = maximize fullscreen
}

windowrule {
  name = localsend
  match:class = ^(localsend)$
  float = on 
  center = on 
  size = 720 480
}
windowrule {
    name = small-file-picker
    match:class = ^(xdg-desktop-portal-gnome)$
    float = 1
    size = 800 600
    center = 1
    pin = on
}

windowrule {
  name = files
  match:class = ^(waypaper)$
  float = on 
  center = on 
  size = 1200 800
}
 
windowrule {
name = brave-pop-up-sign-in-window
match:title = ^(Sign in - Google Accounts|Google Accounts|Sign in|Login|Authorize.*)$
match:class = .*brave.*
float = on
size = 600 450
center = on
pin = on
}

windowrule {
name = brave-file-picker
match:title = ^(.*wants to save.*|Open File|Save File|Save Image|Save As|Select Folder|Enter name of file to save to.*)$
match:class = ^(xdg-desktop-portal-gtk)$
float = on
size = 900 600
center = on
pin = on
}

windowrule {
name = brave-file-input-picker
match:title = ^(.*wants to (open|save).*|Open Files|Open File|Save File|Save Image|Save As|Select Folder.*)$
match:initial_class = ^(xdg-desktop-portal-gtk)$
float = on
size = 900 600
center = on
pin = on
}

windowrule {
name = brave-picture-in-picture
match:title = ^(.*Picture-in-picture)$
match:initial_class = ^$
float = on
pin = on
size = 480 270
keep_aspect_ratio = off
suppress_event = maximize fullscreen
}
