windowrule {
    name = floating-terminals
    match:class = ^(kitty)$
    float = on
    center = on
    size = 1200 800
}

windowrule {
  name = localsend
  match:class = ^(localsend)$
  float = on 
  center = on 
  size = 720 480
}

 windowrule {
    name = zen-pip
    match:title = ^(Picture-in-Picture)$
    float = 1
    pin = 1
    keep_aspect_ratio = 1
    size = 640 360
}

windowrule {
    name = browser-popups
    match:class = ^(pop-up|dialog)$
    float = 1
    center = 1
    size = 800 600
}

windowrule {
  name = files
  match:class = ^(nemo)$
  float = on 
  center = on 
  size = 720 480
}


windowrule {
  name = files
  match:class = ^(waypaper)$
  float = on 
  center = on 
  size = 1200 800
}

