$background = rgb(14161A)
$foreground = rgb(F7F5EA)
$color0 = rgb(3B3D42)
$color1 = rgb(1C2510)
$color2 = rgb(581409)
$color3 = rgb(6D7568)
$color4 = rgb(ED424B)
$color5 = rgb(C48C43)
$color6 = rgb(E9E3C3)
$color7 = rgb(ECE9D9)
$color8 = rgb(A5A398)
$color9 = rgb(1C2510)
$color10 = rgb(581409)
$color11 = rgb(6D7568)
$color12 = rgb(ED424B)
$color13 = rgb(C48C43)
$color14 = rgb(E9E3C3)
$color15 = rgb(ECE9D9)
