$background = rgb(222222)
$foreground = rgb(FDEBCD)
$color0 = rgb(484848)
$color1 = rgb(222222)
$color2 = rgb(601611)
$color3 = rgb(67686A)
$color4 = rgb(A27439)
$color5 = rgb(92A8B5)
$color6 = rgb(F8C771)
$color7 = rgb(F3DBB0)
$color8 = rgb(AA997B)
$color9 = rgb(222222)
$color10 = rgb(601611)
$color11 = rgb(67686A)
$color12 = rgb(A27439)
$color13 = rgb(92A8B5)
$color14 = rgb(F8C771)
$color15 = rgb(F3DBB0)
