source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/decorations.conf
source = ~/.config/hypr/conf/devices.conf
source = ~/.config/hypr/conf/keymaps.conf
source = ~/.config/hypr/conf/windowrules.conf

misc {
    disable_hyprland_logo = true  
  }

master {
    orientation = right 
    slave_count_for_center_master = 0
  }



env = MOZ_ENABLE_WAYLAND,1
