source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/decorations.conf
source = ~/.config/hypr/conf/devices.conf
source = ~/.config/hypr/conf/keymaps.conf
source = ~/.config/hypr/conf/windowrules.conf

misc {
    disable_hyprland_logo = true  
}

render {
    direct_scanout = true
}

env = MOZ_ENABLE_WAYLAND,1


