general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend/hibernate
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after wake
}

# 1. Dim screen (at 60s)
listener {
    timeout = 60
    on-timeout = brightnessctl set 10%
    on-resume = brightnessctl set 100%
}

# 2. Warning notification (at 90s)
listener {
    timeout = 90
    on-timeout = notify-send "System Notice" "Hibernating in 30 seconds..."
}

# 3. Lock Screen (at 110s)
listener {
    timeout = 110
    on-timeout = loginctl lock-session
}


