$font = Monospace


background {
    monitor =
path = /home/vaseline/Pictures/Wallpapers/edwin-rodriguez-DS6lRtglcOM-unsplash.jpg
    color = rgba(0, 0, 0, 1.0)
}



# Date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgba(255, 255, 255, 1.0)
    font_size = 20
    font_family = monospace
    position = 50, -160
    halign = left
    valign = top
}

# Password Input
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 1.0)
    inner_color = rgba(0, 0, 0, 1.0)
    font_color = rgba(255, 255, 255, 1.0)
    fade_on_empty = false
    placeholder_text = <span font_family="monospace" foreground="##ffffff">ENTER PASSWORD</span>
    hide_input = false
    rounding = 2
    position = 0, 100
    halign = center
    valign = bottom
}
