[templates]
hypr = { template = "colors-hyprland.conf", target = "~/.config/hypr/colors.conf" }
waybar = { template = "waybar.css", target = "~/.config/waybar/colors.css" }
kitty = { template = "kitty.conf", target = "~/.config/kitty/kitty.conf" }
kde = { template = "kde.colors", target = "~/.local/share/color-schemes/WallustGenerated.colors" }
gtk = { template = "gtk.css", target = "~/.config/gtk-3.0/gtk.css" }
gtk4 = { template = "gtk.css", target = "~/.config/gtk-4.0/gtk.css" }
qt  = { template = "qt5ct.conf", target = "~/.config/qt5ct/colors/WallustGenerated.conf" }
swaync = { template = "swaync.css", target = "~/.config/swaync/style.css" }
